#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2023 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 0.32.0
# Product:       sfx6xxx
# Model-Version: 2.2.0
#

import argparse
import time
from sensirion_i2c_driver import LinuxI2cTransceiver, I2cConnection, CrcCalculator
from sensirion_driver_adapters.i2c_adapter.i2c_channel import I2cChannel
from sensirion_i2c_sfx6xxx.device import Sfx6xxxDevice

parser = argparse.ArgumentParser()
parser.add_argument('--i2c-port', '-p', default='/dev/i2c-1')
args = parser.parse_args()

with LinuxI2cTransceiver(args.i2c_port) as i2c_transceiver:
    channel = I2cChannel(I2cConnection(i2c_transceiver),
                         slave_address=0x24,
                         crc=CrcCalculator(8, 0x31, 0xff, 0x0))
    sensor = Sfx6xxxDevice(channel)
    (product_identifier, serial_number
     ) = sensor.read_product_identifier()
    print(f"product_identifier: {product_identifier}; "
          f"serial_number: {serial_number}; "
          )
    sensor.start_o2_continuous_measurement()
    for i in range(100):
        try:
            time.sleep(0.5)
            a_flow = sensor.read_flow()
            print(f"a_flow: {a_flow}; "
                  )
        except BaseException:
            continue
    sensor.stop_continuous_measurement()
